<a href="https://colab.research.google.com/github/yuzo-maruyama/quarto_stats/blob/main/JS_JMVA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# $\Psi_1$

\begin{equation}
 \Psi_1(w;a)=\frac{1}{a}\frac{w}{w+1},
\quad\text{and}\quad \phi_1(w)=p-2- \frac{1}{\log(w+1)/a+1/(p-2)},
\end{equation}

In [ ]:
P = 3:15
A = (1:7)/2

In [ ]:
result.lower = matrix(0, length(A), length(P))

In [ ]:
for(i in 1:length(A)){
  for(k in 1:length(P)){
    denominator = function(x){
    dchisq(x,df= P[k]-2) /(1/(P[k]-2) + log(x+1)/A[i])^2
    }
    numerator = function(x){
      denominator(x) * x/(x+1)
    }
  In = integrate(numerator, 0, Inf)
  Id = integrate(denominator, 0, Inf)
  tmp = 4*(1/A[i])*(In$value-In$abs.error)/(Id$value+Id$abs.error)-1
  if(tmp<0){
    result.lower[i, k]=round(tmp,3)
  }else{
    result.lower[i, k]=round(tmp,3)
    break
    }
  }
}

In [ ]:
rownames(result.lower) = as.character(A)
colnames(result.lower) = as.character(P)
result.lower

    3      4      5      6      7      8      9      10     11     12     13
0.5  0.263  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000 0.000
1   -0.160  0.311  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000 0.000
1.5 -0.364 -0.019  0.285  0.000  0.000  0.000  0.000  0.000  0.000  0.000 0.000
2   -0.487 -0.212  0.014  0.000  0.000  0.000  0.000  0.000  0.000  0.000 0.000
2.5 -0.569 -0.339 -0.160 -0.011  0.109  0.000  0.000  0.000  0.000  0.000 0.000
3   -0.628 -0.430 -0.282 -0.162 -0.066  0.008  0.000  0.000  0.000  0.000 0.000
3.5 -0.673 -0.499 -0.372 -0.272 -0.193 -0.132 -0.086 -0.051 -0.024 -0.003 0.013
    14 15
0.5 0  0
1   0  0
1.5 0  0
2   0  0
2.5 0  0
3   0  0
3.5 0  0

# $\Psi_2$

\begin{equation}
 \Psi_2(w;a,b)=\frac{1}{a}\left(\frac{w}{p-2}\right)^b%
 \quad\text{for }a>0,\ b>0,
\quad \text{and}\quad\phi_2(w)=p-2- \frac{1}{ \{w/(p-2)\}^b/(ab)+1/(p-2)},
\end{equation}

In [ ]:
P = 3:300
A = (1:7)/2
B = (1:6)/2

In [ ]:
result.lower = array(0, dim=c(length(P),length(A), length(B)))
result.P = matrix(0, length(A),length(B))

In [ ]:
for(i in 1:length(A)){
  for(j in 1:length(B)){
    for(k in 1:length(P)){
      if(P[k]/2-1-2*B[j]>0){
        y = P[k]/2-1
        tmp = exp(lgamma(y-B[j])-lgamma(y-2*B[j])-B[j]*log(y)-log(A[i]))
#        tmp = gamma(y-B[j])/(gamma(y-2*B[j])*y^(B[j]))/A[i]
        result.lower[k,i,j]=round(4*tmp-1,2)
        if(4*tmp-1>0){
          if(result.P[i,j]==0){
            result.P[i,j]=P[k]
          }
        }
      }
    }
  }
}

In [ ]:
rownames(result.P) = as.character(A)
colnames(result.P) = as.character(B)
result.P

    0.5 1  1.5 2   2.5 3
0.5  5   7 10   14  18  23
1    5   8 12   17  23  30
1.5  5   9 14   21  29  39
2    6  11 17   27  38  51
2.5  6  13 23   36  52  72
3    8  18 34   55  81 112
3.5 13  34 67  111 166 232

In [ ]:
result.PP.2 <- matrix(list(NULL), length(A), length(B))
result.PP.3 <- matrix(list(NULL), length(A), length(B))

In [ ]:
for(i in 1:length(A)){
  for(j in 1:length(B)){
    for(k in (result.P[i,j]):3){
      denominator = function(x){
        dgamma(x,shape=k/2-1, scale=1/(k/2-1))/(1/(k-2) + x^(B[j])/(A[i]*B[j]))^2
      }
      numerator = function(x){
         denominator(x) * x^(B[j])/A[i]
      }
    In = integrate(numerator, 0, Inf)
    Id = integrate(denominator, 0, Inf)

    tmp = 4*(In$value-In$abs.error)/(Id$value+Id$abs.error)-1
    result.PP.3[[i,j]] = c(result.PP.3[[i,j]], round(tmp,2))
    if(tmp>0){
    result.PP.2[[i,j]] = c(result.PP.2[[i,j]],k)
    }
    }
  }
}

In [ ]:
result.PP.2

     [,1]       [,2]                  [,3]
[1,] 5, 4, 3    7, 6, 5, 4, 3         10, 9, 8, 7, 6, 5, 4, 3
[2,] 5, 4, 3    8, 7, 6, 5, 4, 3      12, 11, 10, 9, 8, 7, 6, 5, 4, 3
[3,] 5, 4, 3    9, 8, 7, 6, 5, 4, 3   14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3
[4,] 6, 5, 4    11, 10, 9, 8, 7, 6, 5 17, 16, 15, 14, 13, 12, 11, 10, 9, 8
[5,] 6, 5, 4    13, 12, 11, 10, 9, 8  23, 22, 21, 20, 19, 18, 17, 16, 15
[6,] 8, 7, 6    18, 17, 16, 15, 14    34, 33, 32, 31, 30, 29, 28, 27, 26
[7,] 13, 12, 11 34, 33, 32, 31, 30    67, 66, 65, 64, 63, 62, 61, 60
     [,4]
[1,] 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3
[2,] 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3
[3,] 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 3
[4,] 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14
[5,] 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25
[6,] 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44
[7,] 111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101
     [,5]
[1,] 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3
[2,] 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3
[3,] 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 3
[4,] 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 3
[5,] 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38
[6,] 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67
[7,] 166, 165, 164, 163, 162, 161, 160, 159, 158, 157, 156, 155, 154, 153
     [,6]
[1,] 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3
[2,] 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3
[3,] 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 3
[4,] 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 3
[5,] 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54
[6,] 112, 111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100, 99, 98, 97, 96, 95
[7,] 232, 231, 230, 229, 228, 227, 226, 225, 224, 223, 222, 221, 220, 219, 218, 217

In [ ]:
result.PP.3

     [,1]
[1,] 3.59, 2.51, 1.27
[2,] 1.49, 1.06, 0.54
[3,] 0.74, 0.51, 0.19
[4,] 0.47, 0.35, 0.20, -0.02
[5,] 0.20, 0.11, 0.00, -0.16
[6,] 0.10, 0.06, 0.01, -0.05, -0.14, -0.27
[7,] 0.02, 0.01, 0.00, -0.01, -0.03, -0.05, -0.08, -0.12, -0.17, -0.24, -0.35
     [,2]
[1,] 2.39, 1.93, 1.47, 1.03, 0.65
[2,] 1.15, 0.98, 0.80, 0.62, 0.43, 0.24
[3,] 0.62, 0.54, 0.45, 0.35, 0.24, 0.14, 0.03
[4,] 0.37, 0.32, 0.27, 0.22, 0.16, 0.09, 0.03, -0.05, -0.12
[5,] 0.17, 0.15, 0.12, 0.09, 0.05, 0.02, -0.03, -0.07, -0.12, -0.17, -0.22
[6,] 0.07, 0.06, 0.04, 0.03, 0.01, -0.01, -0.03, -0.05, -0.07, -0.10, -0.13, -0.16, -0.19, -0.23, -0.26, -0.30
[7,] 0.02, 0.01, 0.01, 0.01, 0.00, 0.00, -0.01, -0.01, -0.02, -0.02, -0.03, -0.04, -0.04, -0.05, -0.06, -0.07, -0.08, -0.09, -0.10, -0.11, -0.12, -0.14, -0.15, -0.17, -0.19, -0.21, -0.23, -0.25, -0.28, -0.31, -0.34, -0.37
     [,3]
[1,] 1.98, 1.73, 1.49, 1.25, 1.02, 0.81, 0.63, 0.49
[2,] 0.97, 0.88, 0.78, 0.69, 0.59, 0.49, 0.40, 0.31, 0.23, 0.19
[3,] 0.52, 0.47, 0.43, 0.37, 0.32, 0.27, 0.22, 0.16, 0.11, 0.06, 0.03, 0.02
[4,] 0.28, 0.25, 0.23, 0.20, 0.17, 0.14, 0.10, 0.07, 0.04, 0.00, -0.03, -0.06, -0.09, -0.11, -0.10
[5,] 0.15, 0.13, 0.12, 0.10, 0.09, 0.07, 0.05, 0.04, 0.02, 0.00, -0.03, -0.05, -0.07, -0.09, -0.12, -0.14, -0.16, -0.18, -0.20, -0.21, -0.18
[6,] 0.06, 0.05, 0.05, 0.04, 0.03, 0.03, 0.02, 0.01, 0.00, -0.01, -0.02, -0.03, -0.04, -0.05, -0.06, -0.07, -0.09, -0.10, -0.11, -0.13, -0.14, -0.16, -0.17, -0.19, -0.21, -0.22, -0.24, -0.26, -0.27, -0.28, -0.28, -0.25
[7,] 0.01, 0.01, 0.01, 0.01, 0.01, 0.00, 0.00, 0.00, 0.00, 0.00, -0.01, -0.01, -0.01, -0.01, -0.02, -0.02, -0.02, -0.02, -0.03, -0.03, -0.03, -0.04, -0.04, -0.04, -0.05, -0.05, -0.05, -0.06, -0.06, -0.07, -0.07, -0.07, -0.08, -0.08, -0.09, -0.10, -0.10, -0.11, -0.11, -0.12, -0.13, -0.13, -0.14, -0.15, -0.16, -0.16, -0.17, -0.18, -0.19, -0.20, -0.21, -0.22, -0.23, -0.25, -0.26, -0.27, -0.28, -0.29, -0.31, -0.32, -0.33, -0.34, -0.35, -0.34, -0.31
     [,4]
[1,] 1.77, 1.61, 1.46, 1.31, 1.16, 1.01, 0.87, 0.75, 0.63, 0.53, 0.45, 0.42
[2,] 0.84, 0.79, 0.73, 0.66, 0.60, 0.54, 0.48, 0.42, 0.36, 0.31, 0.25, 0.21, 0.17, 0.15, 0.19
[3,] 0.47, 0.44, 0.41, 0.37, 0.34, 0.31, 0.28, 0.24, 0.21, 0.17, 0.14, 0.11, 0.08, 0.05, 0.02, 0.00, -0.02, -0.01, 0.05
[4,] 0.26, 0.24, 0.23, 0.21, 0.19, 0.17, 0.15, 0.13, 0.12, 0.09, 0.07, 0.05, 0.03, 0.01, -0.01, -0.03, -0.05, -0.07, -0.09, -0.11, -0.13, -0.14, -0.14, -0.12, -0.05
[5,] 0.13, 0.12, 0.11, 0.10, 0.09, 0.08, 0.07, 0.06, 0.05, 0.04, 0.02, 0.01, 0.00, -0.01, -0.03, -0.04, -0.05, -0.07, -0.08, -0.10, -0.11, -0.13, -0.14, -0.16, -0.17, -0.18, -0.20, -0.21, -0.22, -0.23, -0.23, -0.23, -0.20, -0.12
[6,] 0.05, 0.05, 0.04, 0.04, 0.04, 0.03, 0.03, 0.02, 0.02, 0.01, 0.01, 0.00, 0.00, -0.01, -0.02, -0.02, -0.03, -0.03, -0.04, -0.05, -0.05, -0.06, -0.07, -0.08, -0.08, -0.09, -0.10, -0.11, -0.12, -0.13, -0.13, -0.14, -0.15, -0.16, -0.17, -0.18, -0.19, -0.20, -0.21, -0.23, -0.24, -0.25, -0.26, -0.27, -0.28, -0.29, -0.29, -0.30, -0.30, -0.30, -0.29, -0.27, -0.18
[7,] 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.02, -0.02, -0.02, -0.02, -0.02, -0.02, -0.03, -0.03, -0.03, -0.03, -0.03, -0.04, -0.04, -0.04, -0.04, -0.04, -0.05, -0.05, -0.05, -0.05, -0.05, -0.06, -0.06, -0.06, -0.06, -0.07, -0.07, -0.07, -0.07, -0.08, -0.08, -0.08, -0.09, -0.09, -0.09, -0.10, -0.10, -0.10, -0.11, -0.11, -0.11, -0.12, -0.12, -0.13, -0.13, -0.13, -0.14, -0.14, -0.15, -0.15, -0.16, -0.16, -0.17, -0.17, -0.18, -0.18, -0.19, -0.19, -0.20, -0.21, -0.21, -0.22, -0.23, -0.23, -0.24, -0.25, -0.26, -0.26, -0.27, -0.28, -0.29, -0.29, -0.30, -0.31, -0.32, -0.33, -0.33, -0.34, -0.35, -0.36, -0.36, -0.36, -0.36, -0.36, -0.35, -0.32, -0.23
     [,5]
[1,] 1.52, 1.42, 1.31, 1.21, 1.10, 1.00, 0.90, 0.81, 0.72, 0.63, 0.55, 0.48, 0.42, 0.37, 0.35, 0.39
[2,] 0.75, 0.71, 0.67, 0.63, 0.58, 0.54, 0.50, 0.45, 0.41, 0.37, 0.33, 0.29, 0.25, 0.21, 0.18, 0.15, 0.12, 0.10, 0.10, 0.11, 0.20
[3,] 0.41, 0.39, 0.37, 0.35, 0.32, 0.30, 0.28, 0.25, 0.23, 0.21, 0.18, 0.16, 0.13, 0.11, 0.09, 0.06, 0.04, 0.02, 0.00, -0.02, -0.04, -0.05, -0.06, -0.07, -0.06, -0.02, 0.09
[4,] 0.23, 0.22, 0.20, 0.19, 0.18, 0.17, 0.15, 0.14, 0.13, 0.11, 0.10, 0.08, 0.07, 0.05, 0.04, 0.02, 0.01, -0.01, -0.02, -0.04, -0.05, -0.07, -0.08, -0.10, -0.11, -0.13, -0.14, -0.15, -0.16, -0.17, -0.18, -0.18, -0.17, -0.16, -0.11, 0.01
[5,] 0.11, 0.10, 0.10, 0.09, 0.08, 0.08, 0.07, 0.06, 0.06, 0.05, 0.04, 0.03, 0.02, 0.02, 0.01, 0.00, -0.01, -0.02, -0.03, -0.04, -0.05, -0.05, -0.06, -0.07, -0.08, -0.09, -0.10, -0.11, -0.13, -0.14, -0.15, -0.16, -0.17, -0.18, -0.19, -0.20, -0.21, -0.22, -0.23, -0.24, -0.25, -0.25, -0.26, -0.26, -0.27, -0.26, -0.25, -0.23, -0.18, -0.06
[6,] 0.05, 0.04, 0.04, 0.04, 0.03, 0.03, 0.03, 0.02, 0.02, 0.02, 0.01, 0.01, 0.01, 0.00, 0.00, 0.00, -0.01, -0.01, -0.01, -0.02, -0.02, -0.03, -0.03, -0.03, -0.04, -0.04, -0.05, -0.05, -0.06, -0.06, -0.07, -0.07, -0.08, -0.08, -0.09, -0.09, -0.10, -0.10, -0.11, -0.12, -0.12, -0.13, -0.13, -0.14, -0.15, -0.15, -0.16, -0.17, -0.17, -0.18, -0.19, -0.19, -0.20, -0.21, -0.22, -0.22, -0.23, -0.24, -0.25, -0.26, -0.26, -0.27, -0.28, -0.29, -0.29, -0.30, -0.31, -0.31, -0.32, -0.33, -0.33, -0.33, -0.33, -0.33, -0.33, -0.32, -0.29, -0.24, -0.11
[7,] 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.02, -0.02, -0.02, -0.02, -0.02, -0.02, -0.02, -0.02, -0.02, -0.03, -0.03, -0.03, -0.03, -0.03, -0.03, -0.03, -0.03, -0.03, -0.04, -0.04, -0.04, -0.04, -0.04, -0.04, -0.04, -0.05, -0.05, -0.05, -0.05, -0.05, -0.05, -0.05, -0.06, -0.06, -0.06, -0.06, -0.06, -0.06, -0.07, -0.07, -0.07, -0.07, -0.07, -0.07, -0.08, -0.08, -0.08, -0.08, -0.08, -0.09, -0.09, -0.09, -0.09, -0.09, -0.10, -0.10, -0.10, -0.10, -0.11, -0.11, -0.11, -0.11, -0.12, -0.12, -0.12, -0.12, -0.13, -0.13, -0.13, -0.14, -0.14, -0.14, -0.14, -0.15, -0.15, -0.15, -0.16, -0.16, -0.16, -0.17, -0.17, -0.17, -0.18, -0.18, -0.19, -0.19, -0.19, -0.20, -0.20, -0.21, -0.21, -0.21, -0.22, -0.22, -0.23, -0.23, -0.24, -0.24, -0.25, -0.25, -0.26, -0.26, -0.27, -0.27, -0.28, -0.28, -0.29, -0.30, -0.30, -0.31, -0.31, -0.32, -0.32, -0.33, -0.34, -0.34, -0.35, -0.35, -0.36, -0.36, -0.37, -0.38, -0.38, -0.38, -0.39, -0.39, -0.39, -0.39, -0.39, -0.38, -0.36, -0.34, -0.28, -0.15
     [,6]
[1,] 1.38, 1.30, 1.22, 1.14, 1.07, 0.99, 0.92, 0.85, 0.77, 0.71, 0.64, 0.58, 0.52, 0.46, 0.41, 0.36, 0.32, 0.29, 0.28, 0.29, 0.38
[2,] 0.68, 0.65, 0.62, 0.58, 0.55, 0.52, 0.49, 0.46, 0.42, 0.39, 0.36, 0.33, 0.30, 0.27, 0.24, 0.21, 0.18, 0.15, 0.13, 0.10, 0.08, 0.06, 0.05, 0.04, 0.04, 0.05, 0.10, 0.22
[3,] 0.38, 0.36, 0.34, 0.33, 0.31, 0.29, 0.28, 0.26, 0.24, 0.23, 0.21, 0.19, 0.17, 0.15, 0.14, 0.12, 0.10, 0.08, 0.06, 0.05, 0.03, 0.01, -0.01, -0.02, -0.04, -0.05, -0.07, -0.08, -0.09, -0.10, -0.11, -0.11, -0.11, -0.10, -0.08, -0.02, 0.12
[4,] 0.20, 0.19, 0.18, 0.17, 0.16, 0.15, 0.14, 0.13, 0.12, 0.11, 0.10, 0.09, 0.08, 0.07, 0.06, 0.05, 0.04, 0.03, 0.02, 0.01, 0.00, -0.02, -0.03, -0.04, -0.05, -0.06, -0.07, -0.09, -0.10, -0.11, -0.12, -0.13, -0.14, -0.15, -0.16, -0.17, -0.18, -0.19, -0.20, -0.21, -0.21, -0.22, -0.22, -0.22, -0.21, -0.19, -0.16, -0.10, 0.05
[5,] 0.10, 0.10, 0.09, 0.09, 0.08, 0.08, 0.07, 0.07, 0.06, 0.06, 0.05, 0.05, 0.04, 0.03, 0.03, 0.02, 0.02, 0.01, 0.00, 0.00, -0.01, -0.01, -0.02, -0.03, -0.03, -0.04, -0.05, -0.05, -0.06, -0.07, -0.08, -0.08, -0.09, -0.10, -0.11, -0.11, -0.12, -0.13, -0.14, -0.15, -0.15, -0.16, -0.17, -0.18, -0.19, -0.19, -0.20, -0.21, -0.22, -0.23, -0.23, -0.24, -0.25, -0.26, -0.26, -0.27, -0.28, -0.28, -0.29, -0.29, -0.30, -0.30, -0.30, -0.30, -0.29, -0.28, -0.26, -0.23, -0.16, 0.00
[6,] 0.04, 0.04, 0.04, 0.03, 0.03, 0.03, 0.03, 0.02, 0.02, 0.02, 0.02, 0.01, 0.01, 0.01, 0.01, 0.01, 0.00, 0.00, 0.00, -0.01, -0.01, -0.01, -0.01, -0.02, -0.02, -0.02, -0.02, -0.03, -0.03, -0.03, -0.04, -0.04, -0.04, -0.05, -0.05, -0.05, -0.06, -0.06, -0.06, -0.07, -0.07, -0.07, -0.08, -0.08, -0.09, -0.09, -0.09, -0.10, -0.10, -0.11, -0.11, -0.11, -0.12, -0.12, -0.13, -0.13, -0.14, -0.14, -0.15, -0.15, -0.15, -0.16, -0.16, -0.17, -0.17, -0.18, -0.19, -0.19, -0.20, -0.20, -0.21, -0.21, -0.22, -0.22, -0.23, -0.23, -0.24, -0.25, -0.25, -0.26, -0.26, -0.27, -0.28, -0.28, -0.29, -0.29, -0.30, -0.31, -0.31, -0.32, -0.32, -0.33, -0.33, -0.34, -0.34, -0.35, -0.35, -0.36, -0.36, -0.36, -0.36, -0.36, -0.36, -0.36, -0.35, -0.34, -0.32, -0.28, -0.21, -0.05
[7,] 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.01, -0.02, -0.02, -0.02, -0.02, -0.02, -0.02, -0.02, -0.02, -0.02, -0.02, -0.02, -0.02, -0.02, -0.03, -0.03, -0.03, -0.03, -0.03, -0.03, -0.03, -0.03, -0.03, -0.03, -0.03, -0.03, -0.04, -0.04, -0.04, -0.04, -0.04, -0.04, -0.04, -0.04, -0.04, -0.04, -0.04, -0.05, -0.05, -0.05, -0.05, -0.05, -0.05, -0.05, -0.05, -0.05, -0.06, -0.06, -0.06, -0.06, -0.06, -0.06, -0.06, -0.06, -0.06, -0.07, -0.07, -0.07, -0.07, -0.07, -0.07, -0.07, -0.07, -0.08, -0.08, -0.08, -0.08, -0.08, -0.08, -0.08, -0.09, -0.09, -0.09, -0.09, -0.09, -0.09, -0.09, -0.10, -0.10, -0.10, -0.10, -0.10, -0.10, -0.11, -0.11, -0.11, -0.11, -0.11, -0.12, -0.12, -0.12, -0.12, -0.12, -0.12, -0.13, -0.13, -0.13, -0.13, -0.13, -0.14, -0.14, -0.14, -0.14, -0.15, -0.15, -0.15, -0.15, -0.15, -0.16, -0.16, -0.16, -0.16, -0.17, -0.17, -0.17, -0.17, -0.18, -0.18, -0.18, -0.19, -0.19, -0.19, -0.19, -0.20, -0.20, -0.20, -0.21, -0.21, -0.21, -0.22, -0.22, -0.22, -0.23, -0.23, -0.23, -0.24, -0.24, -0.24, -0.25, -0.25, -0.25, -0.26, -0.26, -0.26, -0.27, -0.27, -0.28, -0.28, -0.28, -0.29, -0.29, -0.30, -0.30, -0.31, -0.31, -0.31, -0.32, -0.32, -0.33, -0.33, -0.34, -0.34, -0.35, -0.35, -0.36, -0.36, -0.36, -0.37, -0.37, -0.38, -0.38, -0.39, -0.39, -0.39, -0.40, -0.40, -0.41, -0.41, -0.41, -0.41, -0.41, -0.42, -0.42, -0.41, -0.41, -0.41, -0.40, -0.38, -0.36, -0.32, -0.25, -0.09